---
title: "Untitled"
author: "Joanna Yeung"
date: "3/14/2021"
output: html_document
---

```{r}
LSA3ATAC_summary <- read.table("/rugpfs/fs0/risc_lab/scratch/npagane/analysis/senescence/LSA/LSA3/ATACseqRunSummary.log",skip=38, header=T, skipNul = TRUE)

# removes rows with Abemaciclib samples b/c I'm not interested in that now. 
LSA3ATAC_summary <- LSA3ATAC_summary[-c(1:23), ]
rownames(LSA3ATAC_summary) <- 1:nrow(LSA3ATAC_summary)

# rearrange rows by chronological timepoint
LSA3ATAC_summary <- LSA3ATAC_summary[c(1:3,12:23, 4:11),  ]
rownames(LSA3ATAC_summary) <- 1:nrow(LSA3ATAC_summary)

# set as factor with proper order of levels so that ggplot plots in desired order. 
LSA3ATAC_summary$SAMPLE <- factor(LSA3ATAC_summary$SAMPLE, levels=LSA3ATAC_summary$SAMPLE)
LSA3ATAC_summary$SAMPLE <- gsub("LSA3-", "", LSA3ATAC_summary$SAMPLE)

# specify timepoint category of samples
LSA3ATAC_summary$TIMEPOINT <- c("cycling", rep("Quiescent", 2),rep("day3", 3),rep("day4", 3), rep("day6", 3), rep("day9", 3), rep("day12", 2), rep("day14", 2), rep("day21", 2), rep("day28", 2))

LSA3ATAC_summary$TIMEPOINT <- factor(LSA3ATAC_summary$TIMEPOINT, levels=unique(LSA3ATAC_summary$TIMEPOINT))

LSA3ATAC_summary$EXPERIMENT <- "LSA3"
LSA3ATAC_summary$DRUG <- "Palbociclib"
LSA3ATAC_summary$SEQUENCING_RUN <- "1_08_2020"
```

```{r}
LSA3ATAC_summary2 <- read.table("/rugpfs/fs0/risc_lab/scratch/jyeung/LSA3/ATACseq_pipeline/ATACseqRunSummary.log",skip=38, header=T, skipNul = TRUE)

# remove Abemaciclib samples because we're not interested in those at the moment 
LSA3ATAC_summary2 <- LSA3ATAC_summary2[1:26, ]
LSA3ATAC_summary2$SAMPLE <- gsub("LSA3-", "", LSA3ATAC_summary2$SAMPLE)

# rearrange samples into a order I like
LSA3ATAC_summary2 <- LSA3ATAC_summary2[c(1, 11, 21, 2, 12, 3, 13, 22, 4, 14, 23, 5, 15, 24, 6, 16, 7, 17, 26, 8, 18, 9, 19, 10, 20), ]
rownames(LSA3ATAC_summary2) <- 1:nrow(LSA3ATAC_summary2)

# set as factor with proper order of levels so that ggplot plots in desired order. 
LSA3ATAC_summary2$SAMPLE <- factor(LSA3ATAC_summary2$SAMPLE, levels=LSA3ATAC_summary2$SAMPLE)

# specify timepoint category of samples
LSA3ATAC_summary2$TIMEPOINT <- c(rep("cycling",3), rep("Quiescent", 2),rep("day3", 3),rep("day4", 3), rep("day6", 3), rep("day9", 2), rep("day12", 3), rep("day14", 2), rep("day21", 2), rep("day28", 2))

LSA3ATAC_summary2$TIMEPOINT <- factor(LSA3ATAC_summary2$TIMEPOINT, levels=unique(LSA3ATAC_summary2$TIMEPOINT))

LSA3ATAC_summary2$EXPERIMENT <- "LSA3"
LSA3ATAC_summary2$DRUG <- "Palbociclib"
LSA3ATAC_summary2$SEQUENCING_RUN <- "3_08_2021"
```
```{r}
LSA3_total <- rbind(LSA3ATAC_summary, LSA3ATAC_summary2)
LSA3_total$SAMPLE <- factor(LSA3_total$SAMPLE, levels= c("C-1", "C-2", "C-3", "PS0-1", "PS0-2", "PS3-1", "PS3-2", "PS3-3", "PS4-1", "PS4-2", "PS4-3", "PS6-1", "PS6-2", "PS6-3",  "PS9-1",  "PS9-2", "PS9-3", "PS12-1", "PS12-2", "PS12-3", "PS14-1", "PS14-2", "PS21-1", "PS21-2", "PS28-1", "PS28-2"))
LSA3_Estimated_Library_size <- ggplot(LSA3_total, aes(x=SAMPLE, y=ESTIMATED_LIBRARY_SIZE, colour=TIMEPOINT, label=ESTIMATED_LIBRARY_SIZE)) + geom_point(stat="identity")+
  facet_wrap(~SEQUENCING_RUN)+
  geom_text(position = position_jitter(width=0.15, height=0.15), check_overlap = T)+
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))+
  xlab("Sample") + 
  ylab("") + 
  ggtitle("LSA3 Estimated Library Size for Palbociclib samples") +
  theme(legend.title=element_blank(), legend.position = "bottom")

LSA3_Read_Pairs_postfiltered <- ggplot(LSA3_total, aes(x=SAMPLE, y=READ_PAIRS_POST_FILTER, colour=TIMEPOINT, label=READ_PAIRS_POST_FILTER)) + geom_point(stat="identity")+
  facet_wrap(~SEQUENCING_RUN)+
  geom_text(position = position_jitter(width=0.15, height=0.15), check_overlap = T)+
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))+
  xlab("Sample") + 
  ylab("") + 
  ggtitle("LSA3 Read Pairs Post Filtered for Palbociclib Samples") +
  theme(legend.title=element_blank(), legend.position = "bottom")

LSA3_Raw_Read_Pairs <- ggplot(LSA3_total, aes(x=SAMPLE, y=RAW_READ_PAIRS, colour=TIMEPOINT, label=RAW_READ_PAIRS)) + geom_point(stat="identity")+
  facet_wrap(~SEQUENCING_RUN)+
  geom_text(position = position_jitter(width=0.15, height=0.15), check_overlap = T)+
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))+
  xlab("Sample") + 
  ylab("") + 
  ggtitle("LSA3 Raw Read Pairs for Palbociclib Samples") +
  theme(legend.title=element_blank(), legend.position = "bottom")
```
```{r}
samples <- c("C-1","C-2"," C-3"," PS0-1"," PS0-2"," PS3-1"," PS3-2"," PS3-3"," PS4-1"," PS4-2"," PS4-3"," PS6-1"," PS6-2"," PS6-3"," PS9-1"," PS9-2"," PS9-3"," PS12-1"," PS12-2"," PS12-3"," PS14-1"," PS14-2"," PS21-1"," PS21-2"," PS28-1","PS28-2")
samples <- factor(samples, levels=samples)
quant <- c(NA, 3.41, NA, 12.62, 7.09, 9.44, 6.86, 12.90, 20.56, 12.01, 6.50, 6.10, 9.05, 13.63, 11.85, 14.68, 5.65, 6.97, 7.55, NA, 6.16, 4.66, 6.73, 6.53, 15.18, 9.36)
Library_conc <- data.frame(SAMPLE=samples, nM=quant, TIMEPOINT=c(rep("cycling",3), rep("Quiescent", 2),rep("day3", 3),rep("day4", 3), rep("day6", 3), rep("day9", 3), rep("day12", 3), rep("day14", 2), rep("day21", 2), rep("day28", 2)))
Library_conc$TIMEPOINT <- factor(Library_conc$TIMEPOINT, levels=unique(Library_conc$TIMEPOINT))

Library_conc_plot <- ggplot(Library_conc, aes(x=SAMPLE, y=nM, fill=TIMEPOINT, label=nM)) + geom_bar(stat="identity")+
  geom_text(position = position_jitter(width=0.15, height=0.15), check_overlap = T)+
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))+
  xlab("Sample") + 
  ylab("Library concentration in nM") + 
  ggtitle("LSA3 Library Concentration for Palbociclib Samples- Dec 2019") +
  theme(legend.title=element_blank(), legend.position = "bottom")
```




